<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>e</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(
		 how to\s+
		|if\b .* \bthen\b
		|repeat\b .*
		|while\b .*
		|try\b .*)
	</string>
	<key>foldingStopMarker</key>
	<string>^\s*(end|done|ok|finished|OK)\b.*$</string>
	<key>keyEquivalent</key>
	<string>~@E</string>
	<key>name</key>
	<string>EnglishScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|then|do)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(let|be|less|smaller|or)\b</string>
			<key>name</key>
			<string>storage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:from|to|at|in|by|of|about|above|after|against|apart\s+from|around|as|aside\s+from|at|before|behind|below|beneath|beside|between|considering|from||in|instead\s+of|into|of|on|onto|out\s+of|over|since|through|thru|to|with|without)\b</string>
			<key>name</key>
			<string>variable.language.prepositions.en</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|of|a|the|default|finally|is|end|ok|done|endif|OK)\b</string>
			<key>name</key>
			<string>storage.type.method</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true)\b</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*|#.*|/\*.*\*/|--.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(100|bla|var)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.js</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.js</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.method</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match regular function like: function myFunc(arg) { … }</string>
			<key>match</key>
			<string>\b(function|define|how to|def|method|public void)\b\s+([a-zA-Z]+\s*)*\s*\b(a|the)\b</string>
			<key>name</key>
			<string>meta.function.js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.englishScript</string>
	<key>uuid</key>
	<string>82344575-61EC-45EF-BB84-6662B5C9062A</string>
</dict>
</plist>
