<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>e</string>
			<string>an</string>
			<string>ang</string>
			<string>ni</string>
			 <string>nis</string>
			<string>angle</string>
		</array>

		<key>name</key>
		<string>EnglishScript</string>

<!-- not used in intellij :(-->
		<key>foldingStartMarker</key>
		<string>do</string>
		<key>foldingStopMarker</key>
		<string>end</string>

		<key>foldingStartMarker</key>
		<string>{</string>
		<key>foldingStopMarker</key>
		<string>}</string>

		<!--<dict>-->
		<!--<key>include</key>-->
		<!--<string>source.js</string>-->
		<!--</dict>-->

		<key>patterns</key>
		<array>

			<dict>
				<key>match</key>
				<string>#.*|//.*</string>
				<key>name</key>
				<string>comment.line</string>
			</dict>

			<dict>
				<key>begin</key>
				<string>/\*</string>
				<key>end</key>
				<string>\*/</string>
				<key>foldingStartMarker</key>
				<string>/\*</string>
				<key>foldingStopMarker</key>
				<string>\*/</string>
				<key>name</key>
				<string>comment.block</string>
			</dict>

			<dict>
				<key>begin</key>
				<string>&lt;!--</string>
				<key>end</key>
				<string>--!&gt;</string>
				<key>name</key>
				<string>comment.html</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>support.function.delimiter.angle</string>
					</dict>
				</dict>
				<key>match</key>
				<string>([\[\]\{\},\(\):])</string>
				<key>name</key>
				<string>constant.language.delimiter.angle</string>
			</dict>

			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.entity.angle</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.entity.angle</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(`)[a-zA-Z_']*?(`)</string>
				<key>name</key>
				<string>keyword.operator.function.infix.angle</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\(\)</string>
				<key>name</key>
				<string>constant.language.unit.angle</string>
			</dict>
			<dict>
				<key>comment</key>
				<string>Floats are always decimal</string>
				<key>match</key>
				<string>\b([0-9]+\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)\b</string>
				<key>name</key>
				<string>constant.numeric.float.angle</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b([0-9]+)\b</string>
				<key>name</key>
				<string>constant.numeric.angle</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>"""</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.angle</string>
					</dict>
				</dict>
				<key>end</key>
				<string>"""</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.angle</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.double.angle</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\'\&amp;])</string>
						<key>name</key>
						<string>constant.character.escape.angle</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\^[A-Z@\[\]\\\^_]</string>
						<key>name</key>
						<string>constant.character.escape.control.angle</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>"</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.angle</string>
					</dict>
				</dict>
				<key>end</key>
				<string>"</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.angle</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.double.angle</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\\"'\&amp;])</string>
						<key>name</key>
						<string>constant.character.escape.angle</string>
					</dict>
					<dict>
						<key>match</key>
						<string>\^[A-Z@\[\]\\\^_]</string>
						<key>name</key>
						<string>constant.character.escape.control.angle</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.angle</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>constant.character.escape.angle</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.angle</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(?x)
					(')
					(?:
					[\ -\[\]-~]								# Basic Char
					| (\\(?:NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE
					|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS
					|US|SP|DEL|[abfnrtv\\\"'\&amp;]))		# Escapes
					| (\^[A-Z@\[\]\\\^_])						# Control Chars
					)
					(')</string>
				<key>name</key>
				<string>string.quoted.single.angle</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b[A-Z]\w*\b</string>
				<key>name</key>
				<string>constant.other.angle</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#comments</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^[a-z][A-Za-z0-9_']*\s+</string>
				<key>name</key>
				<string>entity.name.function.angle</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#infix_op</string>
			</dict>
			<dict>
				<key>match</key>
				<string>[|!%$?~+:\-.=&lt;/&gt;&amp;\\*^]+</string>
				<key>name</key>
				<string>keyword.operator.angle</string>
			</dict>
			<dict>
				<key>match</key>
				<string>([\(\)])</string>
				<key>name</key>
				<string>keyword.other.parenthesis.angle</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(define|def|if|while|for|return|result|import|export|it|out|but|not|neither|nor|and|or|xor|then|do|otherwise|as|default|finally|end|ok|done|endif|OK|macro|once|whenever|type|print|rescue|assert)\b</string>
				<key>name</key>
				<string>keyword.construct</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(new|is|as|using|checked|unchecked|typeof|sizeof)\b</string>
				<key>name</key>
				<string>keyword.operator</string>
			</dict>

		<!--</array>-->
	<!--<array>-->

			<dict>
				<key>foldingStartMarker</key>
				<string>\{\s*$</string>
				<key>foldingStopMarker</key>
				<string>^\s*\}</string>
				<key>match</key>
				<string>function\s+([A-Za-z_]*)</string>
				<key>name</key>
				<string>meta.resource.angle</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(to|def|function)\b</string>
				<key>name</key>
				<!--<string>storage.type.function.angle</string>-->
				<!--<string>function.language</string>-->
				<!--<string>keyword.x</string>-->
				<string>definition.x</string>
			</dict>

			<!--<dict>-->
				<!--<key>match</key>-->
				<!--<string>(?set|let|var|val|const)\b([A-Za-z_])*</string>-->
				<!--<key>name</key>-->
				<!--<string>variable</string>-->
			<!--</dict>-->

			<!--<dict>-->
				<!--<key>match</key>-->
				<!--<string>-->
					<!--\b(if|else|while|for|foreach|in|do|return|continue|break|switch|case|default|goto|throw|try|catch|finally|lock|yield)\b-->
				<!--</string>-->
				<!--<key>name</key>-->
				<!--<string>keyword.control</string>-->
			<!--</dict>-->

			<dict>
				<key>match</key>
				<string>\b(from|where|select|group|into|orderby|join|let|on|equals|by)\b</string>
				<key>name</key>
				<string>keyword.linq</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(new|is|as|using|checked|unchecked|typeof|sizeof)\b</string>
				<key>name</key>
				<string>keyword.operator</string>
			</dict>

			<!--<dict>-->
				<!--<key>match</key>-->
				<!--<string>\b(def)\b</string>-->
				<!--<key>name</key>-->
				<!--<string>keyword</string>-->
			<!--</dict>-->

			<dict>
				<key>match</key>
				<string>\b(float|string)\b</string>
				<key>name</key>
				<string>constant.type</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(var|event|delegate|add|remove|set|get|value)\b</string>
				<key>name</key>
				<string>keyword.other</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(let|set|var|val|less|smaller|equal|equals|same)\b</string>
				<key>name</key>
				<string>storage</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(null|nill|nil|none|true|false|pi|\d+|one|two|zero|100|infinity|π)\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(\+|-)?(0(x|X)[0-9a-fA-F]*)|([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(\w+)?\b</string>
				<key>name</key>
				<string>constant.numeric.source</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(my|result|it|your|anything|true|false|yes|no|nil|null|nix|nill|nil|none|no|null|any|all|some|this|base|super)\b</string>
				<key>name</key>
				<string>constant.language</string>
			</dict>


			<dict>
				<key>match</key>
				<string>var\s+([a-z]+)\b</string>
				<key>name</key>
				<string>variable.language</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(x|y|z|i)\b</string>
				<key>name</key>
				<string>variable.language1</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(at|in|by|of|about|above|after|against|apart|around|as|as|before|behind|below|beneath|beside|between|considering|from|in|instead|into|of|on|onto|over|since|through|thru|to|with|without)\b</string>
				<key>name</key>
				<string>keyword.preposition</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(=|be|is|are|equals|to)\b</string>
				<key>name</key>
				<string>article.equals</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(a|an|the|you|that|this|these|those|such|many|most|all|any)\b</string>
				<key>name</key>
				<string>article</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(bool|byte|sbyte|char|decimal|double|float|int|uint|long|ulong|object|short|ushort|string|void|class|struct|enum|interface|number|real|bigint|integer|boolean|character|word|item)\b</string>
				<key>name</key>
				<string>keyword.storage.type</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(event|delegate|internal|public|protected|private|static|const|constant|new|sealed|abstract|virtual|override|extern|unsafe|readonly|volatile|implicit|explicit|operator)\b</string>
				<key>name</key>
				<string>storage.modifier</string>
			</dict>



			<!--<dict>-->
				<!--<key>begin</key>-->
				<!--<string>\{</string>-->
				<!--<key>end</key>-->
				<!--<string>\}</string>-->
				<!--<key>name</key>-->
				<!--<string>function.body</string>-->
			<!--</dict>-->



			<dict>
				<key>begin</key>
				<string>`</string>
				<key>end</key>
				<string>`</string>
				<key>name</key>
				<string>string.quoted.template</string>
			</dict>

			<dict>
				<key>begin</key>
				<string>"</string>
				<key>end</key>
				<string>"</string>
				<key>name</key>
				<string>string.quoted.double</string>
			</dict>

			<dict>
				<key>begin</key>
				<string>'</string>
				<key>end</key>
				<string>'</string>
				<key>name</key>
				<string>string.quoted.single</string>
			</dict>


			<dict>
				<key>match</key>
				<string>(\b|\s)(!important|for|do|end|in|return|if|else|unless|return)\b</string>
				<key>name</key>
				<string>keyword.control.stylus</string>
			</dict>

			<!--<dict>-->
				<!--<key>match</key>-->
				<!--<string>(!|~|\+|-|(?:\*)?\*|\/|%|(?:\.)\.\.|&lt;|&gt;|(?:=|:|\?|\+|-|\*|\/|%|&lt;|&gt;)?=|!=)</string>-->
				<!--<key>name</key>-->
				<!--<string>keyword.operator.sigil</string>-->
			<!--</dict>-->


			<dict>
				<key>comment</key>
				<string>Hex numbers</string>
				<key>match</key>
				<string>\b(0x[0-9A-Fa-f]+)\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(and|or|xor|not|in|is|equals|type alias|type|case)\b</string>
				<key>name</key>
				<string>keyword.operator.english</string>
			</dict>

			<dict>
				<key>match</key>
				<string>def\s\b([a-z][A-Za-z0-9_']*)\b</string>
				<key>name</key>
				<string>entity.name.function.angle</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b[a-z][A-Za-z0-9_']*\b</string>
				<key>name</key>
				<string>entity.name</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b(\w+)\b</string>
				<key>name</key>
				<string>variable.unknown</string>
			</dict>

<!-- matches -->
		</array>

	<key>repository</key>
	<dict>
		<key>scriptblock</key>
		<dict>
			<key>begin</key>
			<string>\\{</string>
			<key>end</key>
			<string>\\}</string>
			<key>name</key>
			<string>meta.scriptblock</string>
		</dict>
	</dict>

		<key>scopeName</key>
		<string>source.englishScript</string>
		<key>uuid</key>
		<string>82344575-61EC-45EF-BB84-6662B5C9062A</string>
	</dict>
</plist>
